server:
  port: 1234
  servlet:
    contextPath: /ecommerce
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/ecommerce_db?user=root
    driverClassName: com.mysql.cj.jdbc.Driver

